### ISSUE TITLE
Great initiative to provide example code - but what is the license for the code?

### ISSUE THREAD

**Issue by joakimeriksson** [Vasakronan/Idun-Examples#6]
I would suggest a very open and permissive such as BSD or MIT.

**Comment by perkarlberg** [comment]
General License structure is applied and MIT is applied wherever possible. We will go through remaining examples one-by-one to verify that MIT can be applied without Idun breaking any underlying licenses.

See: https://github.com/Vasakronan/Idun-Examples/pull/7
